/* eslint-disable */
/**
 * Generated `api` utility — build stub.
 * Real version is generated by `npx convex dev`.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = new Proxy({}, {
  get: (_t, p) => new Proxy({ _name: String(p) }, {
    get: (_t2, p2) => ({ _type: "ref", _name: `${String(p)}:${String(p2)}` }),
  }),
});

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const internal: any = api;
